version: '3'
services:
  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  app:
    command: bash -c "rm tmp/pids/server.pid; bundle exec rails s -p 5000 -b '0.0.0.0'"

