version: '3'
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: db
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
